service: cdop-backend
frameworkVersion: "4"

plugins:
  - serverless-wsgi
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: python3.13
  region: ap-southeast-2
  memorySize: 512
  timeout: 180
  layers:
    - arn:aws:lambda:ap-southeast-2:539247469538:layer:DependencyLayer:8

  # vpc:
  #   securityGroupIds:
  #     - sg-00f218b4fb5bfdd4c
  #   subnetIds:
  #     - subnet-0eb51aec86119b476

  iam:
    role:
      statements:
        # DynamoDB permissions
        - Effect: Allow
          Action:
            - dynamodb:DescribeTable
            - dynamodb:PutItem
            - dynamodb:GetItem
            - dynamodb:DeleteItem
            - dynamodb:Scan
          Resource: arn:aws:dynamodb:ap-southeast-2:539247469538:table/TargetEmbeddings
        # S3 permissions
        - Effect: Allow
          Action:
            - s3:GetObject
            - s3:PutObject
            - s3:ListBucket
          Resource:
            - arn:aws:s3:::${env:S3_BUCKET_NAME}
            - arn:aws:s3:::${env:S3_BUCKET_NAME}/*
        # EventBridge publish permissions
        - Effect: Allow
          Action:
            - events:PutEvents
            - events:PutEvent
            - events:DescribeEventBus
            - events:ListEventBuses
          Resource:
            - arn:aws:events:ap-southeast-2:539247469538:event-bus/default
        # Bedrock permissions
        - Effect: Allow
          Action:
            - bedrock:InvokeModel
            - bedrock:InvokeModelWithResponseStream
          Resource: "arn:aws:bedrock:ap-southeast-2::foundation-model/*"
        - Effect: Allow
          Action:
            - bedrock-runtime:InvokeModel
          Resource: "arn:aws:bedrock-runtime:ap-southeast-2::foundation-model/*"

  environment:
    S3_BUCKET_NAME: ${env:S3_BUCKET_NAME}
    MYSQL_HOST: ${env:MYSQL_HOST}
    MYSQL_PORT: ${env:MYSQL_PORT}
    MYSQL_USER: ${env:MYSQL_USER}
    MYSQL_PASSWORD: ${env:MYSQL_PASSWORD}
    MYSQL_DATABASE: ${env:MYSQL_DATABASE}
    JWT_SECRET_KEY: ${env:JWT_SECRET_KEY}
    JWT_EXPIRED_IN_HOURS: ${env:JWT_EXPIRED_IN_HOURS}
    WEB3_PROVIDER_URL: ${env:WEB3_PROVIDER_URL}
    EXPLORER_TX_PREFIX: ${env:EXPLORER_TX_PREFIX}
    PRIVATE_KEY: ${env:PRIVATE_KEY}
    CONTRACT_ADDRESS: ${env:CONTRACT_ADDRESS}
    DYNAMODB_TABLE: ${env:DYNAMODB_TABLE}
    OPENAI_API_KEY: ${env:OPENAI_API_KEY}
    BEDROCK_EMBED_MODEL_ID: ${env:BEDROCK_EMBED_MODEL_ID}

custom:
  wsgi:
    app: app.app
    packRequirements: false
  dotenv:
    path: .env

package:
  exclude:
    - node_modules/**
    - venv/**
    - .env
    - tests/**
    - __pycache__/**
    - layer/**
    - layer.zip
  include:
    - app/**

functions:
  getOrganizationList:
    handler: app/wsgi_handler.handler
    events:
      - httpApi:
          method: GET
          path: /organizations

  getCampaignList:
    handler: app/wsgi_handler.handler
    events:
      - httpApi:
          method: GET
          path: /campaigns

  fallback:
    handler: app/wsgi_handler.handler
    events:
      - httpApi:
          method: ANY
          path: /{proxy+}

  # embeddingHandler:
  #   handler: app/src/jobs/writeEmbedding.write_embedding
  #   events:
  #     - eventBridge:
  #         eventBus: default
  #         pattern:
  #           source:
  #             - "myapp.data"
  #           detail-type:
  #             - "EntityChanged"
